spring:
  application:
    name: diary-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.128:8848
        namespace: b78c8d52-3fc3-4276-9cbb-0f2efd326481
      config:
        server-addr: 192.168.101.128:8848
        namespace: b78c8d52-3fc3-4276-9cbb-0f2efd326481
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
  config:
    import:
      - optional:nacos:data.yaml?group=DEFAULT_GROUP&namespace=b78c8d52-3fc3-4276-9cbb-0f2efd326481
server:
  port: 8801