CREATE TABLE `ingredient` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` varchar(50) NOT NULL COMMENT '食材名称',
    `category` varchar(20) NOT NULL COMMENT '分类：vegetable/meat/egg/seafood/bean/staple/seasoning',
    `category_name` varchar(20) NOT NULL COMMENT '分类名称（中文）：蔬菜/肉类/蛋类/水产/豆制品/主食/调料',
    `is_main` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否主料：1是主料，0是配料/调料',
    `icon_id` bigint(20) DEFAULT NULL COMMENT '图标ID，关联图标表主键',
    `user_id` bigint(20) NOT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_category` (`category`),
    KEY `idx_is_main` (`is_main`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='食材表';

INSERT INTO `ingredient` (`name`, `category`, `category_name`, `is_main`, `icon_id`, `user_id`) VALUES

-- ==================== 蔬菜类 ====================
('白菜', 'vegetable', '蔬菜', 1, NULL, 1),
('菠菜', 'vegetable', '蔬菜', 1, NULL, 1),
('油菜', 'vegetable', '蔬菜', 1, NULL, 1),
('生菜', 'vegetable', '蔬菜', 1, NULL, 1),
('娃娃菜', 'vegetable', '蔬菜', 1, NULL, 1),
('韭菜', 'vegetable', '蔬菜', 1, NULL, 1),
('芹菜', 'vegetable', '蔬菜', 1, NULL, 1),
('香菜', 'vegetable', '蔬菜', 0, NULL, 1),
('西红柿', 'vegetable', '蔬菜', 1, NULL, 1),
('黄瓜', 'vegetable', '蔬菜', 1, NULL, 1),
('冬瓜', 'vegetable', '蔬菜', 1, NULL, 1),
('南瓜', 'vegetable', '蔬菜', 1, NULL, 1),
('苦瓜', 'vegetable', '蔬菜', 1, NULL, 1),
('丝瓜', 'vegetable', '蔬菜', 1, NULL, 1),
('茄子', 'vegetable', '蔬菜', 1, NULL, 1),
('青椒', 'vegetable', '蔬菜', 1, NULL, 1),
('红椒', 'vegetable', '蔬菜', 1, NULL, 1),
('黄椒', 'vegetable', '蔬菜', 1, NULL, 1),
('尖椒', 'vegetable', '蔬菜', 1, NULL, 1),
('小米辣', 'vegetable', '蔬菜', 0, NULL, 1),
('土豆', 'vegetable', '蔬菜', 1, NULL, 1),
('红薯', 'vegetable', '蔬菜', 1, NULL, 1),
('紫薯', 'vegetable', '蔬菜', 1, NULL, 1),
('山药', 'vegetable', '蔬菜', 1, NULL, 1),
('芋头', 'vegetable', '蔬菜', 1, NULL, 1),
('莲藕', 'vegetable', '蔬菜', 1, NULL, 1),
('白萝卜', 'vegetable', '蔬菜', 1, NULL, 1),
('红萝卜', 'vegetable', '蔬菜', 1, NULL, 1),
('胡萝卜', 'vegetable', '蔬菜', 1, NULL, 1),
('花菜', 'vegetable', '蔬菜', 1, NULL, 1),
('西兰花', 'vegetable', '蔬菜', 1, NULL, 1),
('莴笋', 'vegetable', '蔬菜', 1, NULL, 1),
('芦笋', 'vegetable', '蔬菜', 1, NULL, 1),
('竹笋', 'vegetable', '蔬菜', 1, NULL, 1),
('茭白', 'vegetable', '蔬菜', 1, NULL, 1),
('豌豆', 'vegetable', '蔬菜', 1, NULL, 1),
('四季豆', 'vegetable', '蔬菜', 1, NULL, 1),
('豇豆', 'vegetable', '蔬菜', 1, NULL, 1),
('毛豆', 'vegetable', '蔬菜', 1, NULL, 1),
('蚕豆', 'vegetable', '蔬菜', 1, NULL, 1),
('黄豆芽', 'vegetable', '蔬菜', 1, NULL, 1),
('绿豆芽', 'vegetable', '蔬菜', 1, NULL, 1),
('洋葱', 'vegetable', '蔬菜', 1, NULL, 1),
('大蒜', 'vegetable', '蔬菜', 0, NULL, 1),
('蒜苗', 'vegetable', '蔬菜', 1, NULL, 1),
('蒜薹', 'vegetable', '蔬菜', 1, NULL, 1),
('生姜', 'vegetable', '蔬菜', 0, NULL, 1),
('大葱', 'vegetable', '蔬菜', 0, NULL, 1),
('小葱', 'vegetable', '蔬菜', 0, NULL, 1),
('菌菇类', 'vegetable', '蔬菜', 1, NULL, 1),
('香菇', 'vegetable', '蔬菜', 1, NULL, 1),
('平菇', 'vegetable', '蔬菜', 1, NULL, 1),
('金针菇', 'vegetable', '蔬菜', 1, NULL, 1),
('杏鲍菇', 'vegetable', '蔬菜', 1, NULL, 1),
('茶树菇', 'vegetable', '蔬菜', 1, NULL, 1),
('口蘑', 'vegetable', '蔬菜', 1, NULL, 1),
('木耳', 'vegetable', '蔬菜', 1, NULL, 1),
('银耳', 'vegetable', '蔬菜', 1, NULL, 1),
('玉米', 'vegetable', '蔬菜', 1, NULL, 1),
('秋葵', 'vegetable', '蔬菜', 1, NULL, 1),

-- ==================== 肉类 ====================
('猪肉', 'meat', '肉类', 1, NULL, 1),
('五花肉', 'meat', '肉类', 1, NULL, 1),
('里脊肉', 'meat', '肉类', 1, NULL, 1),
('排骨', 'meat', '肉类', 1, NULL, 1),
('猪蹄', 'meat', '肉类', 1, NULL, 1),
('猪肝', 'meat', '肉类', 1, NULL, 1),
('猪肚', 'meat', '肉类', 1, NULL, 1),
('牛肉', 'meat', '肉类', 1, NULL, 1),
('牛腩', 'meat', '肉类', 1, NULL, 1),
('牛腱子', 'meat', '肉类', 1, NULL, 1),
('牛里脊', 'meat', '肉类', 1, NULL, 1),
('羊肉', 'meat', '肉类', 1, NULL, 1),
('羊排', 'meat', '肉类', 1, NULL, 1),
('鸡肉', 'meat', '肉类', 1, NULL, 1),
('鸡胸肉', 'meat', '肉类', 1, NULL, 1),
('鸡腿', 'meat', '肉类', 1, NULL, 1),
('鸡翅', 'meat', '肉类', 1, NULL, 1),
('鸡爪', 'meat', '肉类', 1, NULL, 1),
('鸭肉', 'meat', '肉类', 1, NULL, 1),
('鸭腿', 'meat', '肉类', 1, NULL, 1),
('鹅肉', 'meat', '肉类', 1, NULL, 1),
('鸽子', 'meat', '肉类', 1, NULL, 1),

-- ==================== 蛋类 ====================
('鸡蛋', 'egg', '蛋类', 1, NULL, 1),
('鸭蛋', 'egg', '蛋类', 1, NULL, 1),
('鹅蛋', 'egg', '蛋类', 1, NULL, 1),
('鹌鹑蛋', 'egg', '蛋类', 1, NULL, 1),
('皮蛋', 'egg', '蛋类', 1, NULL, 1),
('咸鸭蛋', 'egg', '蛋类', 1, NULL, 1),

-- ==================== 水产类 ====================
('草鱼', 'seafood', '水产', 1, NULL, 1),
('鲤鱼', 'seafood', '水产', 1, NULL, 1),
('鲫鱼', 'seafood', '水产', 1, NULL, 1),
('鲈鱼', 'seafood', '水产', 1, NULL, 1),
('鲶鱼', 'seafood', '水产', 1, NULL, 1),
('黑鱼', 'seafood', '水产', 1, NULL, 1),
('黄鱼', 'seafood', '水产', 1, NULL, 1),
('带鱼', 'seafood', '水产', 1, NULL, 1),
('鲳鱼', 'seafood', '水产', 1, NULL, 1),
('鳕鱼', 'seafood', '水产', 1, NULL, 1),
('三文鱼', 'seafood', '水产', 1, NULL, 1),
('虾', 'seafood', '水产', 1, NULL, 1),
('基围虾', 'seafood', '水产', 1, NULL, 1),
('小龙虾', 'seafood', '水产', 1, NULL, 1),
('螃蟹', 'seafood', '水产', 1, NULL, 1),
('大闸蟹', 'seafood', '水产', 1, NULL, 1),
('蛤蜊', 'seafood', '水产', 1, NULL, 1),
('花蛤', 'seafood', '水产', 1, NULL, 1),
('蛏子', 'seafood', '水产', 1, NULL, 1),
('生蚝', 'seafood', '水产', 1, NULL, 1),
('扇贝', 'seafood', '水产', 1, NULL, 1),
('鲍鱼', 'seafood', '水产', 1, NULL, 1),
('鱿鱼', 'seafood', '水产', 1, NULL, 1),
('墨鱼', 'seafood', '水产', 1, NULL, 1),
('海带', 'seafood', '水产', 1, NULL, 1),
('紫菜', 'seafood', '水产', 1, NULL, 1),

-- ==================== 豆制品 ====================
('豆腐', 'bean', '豆制品', 1, NULL, 1),
('嫩豆腐', 'bean', '豆制品', 1, NULL, 1),
('老豆腐', 'bean', '豆制品', 1, NULL, 1),
('豆腐干', 'bean', '豆制品', 1, NULL, 1),
('豆腐皮', 'bean', '豆制品', 1, NULL, 1),
('腐竹', 'bean', '豆制品', 1, NULL, 1),
('油豆腐', 'bean', '豆制品', 1, NULL, 1),
('豆泡', 'bean', '豆制品', 1, NULL, 1),
('豆浆', 'bean', '豆制品', 1, NULL, 1),
('豆豉', 'bean', '豆制品', 0, NULL, 1),
('腐乳', 'bean', '豆制品', 0, NULL, 1),

-- ==================== 主食类 ====================
('大米', 'staple', '主食', 1, NULL, 1),
('糯米', 'staple', '主食', 1, NULL, 1),
('小米', 'staple', '主食', 1, NULL, 1),
('黑米', 'staple', '主食', 1, NULL, 1),
('面粉', 'staple', '主食', 1, NULL, 1),
('面条', 'staple', '主食', 1, NULL, 1),
('挂面', 'staple', '主食', 1, NULL, 1),
('方便面', 'staple', '主食', 1, NULL, 1),
('馒头', 'staple', '主食', 1, NULL, 1),
('花卷', 'staple', '主食', 1, NULL, 1),
('包子', 'staple', '主食', 1, NULL, 1),
('饺子皮', 'staple', '主食', 1, NULL, 1),
('馄饨皮', 'staple', '主食', 1, NULL, 1),
('年糕', 'staple', '主食', 1, NULL, 1),
('米粉', 'staple', '主食', 1, NULL, 1),
('粉丝', 'staple', '主食', 1, NULL, 1),
('红薯粉', 'staple', '主食', 1, NULL, 1),

-- ==================== 调料类（is_main=0） ====================
('盐', 'seasoning', '调料', 0, NULL, 1),
('糖', 'seasoning', '调料', 0, NULL, 1),
('冰糖', 'seasoning', '调料', 0, NULL, 1),
('红糖', 'seasoning', '调料', 0, NULL, 1),
('生抽', 'seasoning', '调料', 0, NULL, 1),
('老抽', 'seasoning', '调料', 0, NULL, 1),
('酱油', 'seasoning', '调料', 0, NULL, 1),
('蚝油', 'seasoning', '调料', 0, NULL, 1),
('料酒', 'seasoning', '调料', 0, NULL, 1),
('米醋', 'seasoning', '调料', 0, NULL, 1),
('陈醋', 'seasoning', '调料', 0, NULL, 1),
('白醋', 'seasoning', '调料', 0, NULL, 1),
('香油', 'seasoning', '调料', 0, NULL, 1),
('花椒油', 'seasoning', '调料', 0, NULL, 1),
('辣椒油', 'seasoning', '调料', 0, NULL, 1),
('食用油', 'seasoning', '调料', 0, NULL, 1),
('花生油', 'seasoning', '调料', 0, NULL, 1),
('大豆油', 'seasoning', '调料', 0, NULL, 1),
('橄榄油', 'seasoning', '调料', 0, NULL, 1),
('猪油', 'seasoning', '调料', 0, NULL, 1),
('花椒', 'seasoning', '调料', 0, NULL, 1),
('八角', 'seasoning', '调料', 0, NULL, 1),
('桂皮', 'seasoning', '调料', 0, NULL, 1),
('香叶', 'seasoning', '调料', 0, NULL, 1),
('干辣椒', 'seasoning', '调料', 0, NULL, 1),
('辣椒粉', 'seasoning', '调料', 0, NULL, 1),
('胡椒粉', 'seasoning', '调料', 0, NULL, 1),
('五香粉', 'seasoning', '调料', 0, NULL, 1),
('孜然粉', 'seasoning', '调料', 0, NULL, 1),
('花椒粉', 'seasoning', '调料', 0, NULL, 1),
('咖喱粉', 'seasoning', '调料', 0, NULL, 1),
('姜黄粉', 'seasoning', '调料', 0, NULL, 1),
('淀粉', 'seasoning', '调料', 0, NULL, 1),
('玉米淀粉', 'seasoning', '调料', 0, NULL, 1),
('红薯淀粉', 'seasoning', '调料', 0, NULL, 1),
('泡打粉', 'seasoning', '调料', 0, NULL, 1),
('小苏打', 'seasoning', '调料', 0, NULL, 1),
('酵母', 'seasoning', '调料', 0, NULL, 1),
('芝麻', 'seasoning', '调料', 0, NULL, 1),
('芝麻酱', 'seasoning', '调料', 0, NULL, 1),
('花生酱', 'seasoning', '调料', 0, NULL, 1),
('豆瓣酱', 'seasoning', '调料', 0, NULL, 1),
('甜面酱', 'seasoning', '调料', 0, NULL, 1),
('番茄酱', 'seasoning', '调料', 0, NULL, 1),
('沙拉酱', 'seasoning', '调料', 0, NULL, 1),
('芥末', 'seasoning', '调料', 0, NULL, 1);