-- 饮食记录模块标准表结构（与前端字段及 DietMapper.xml 对齐）
CREATE TABLE IF NOT EXISTS `diet_record` (
    `id`              BIGINT UNSIGNED NOT NULL COMMENT '雪花主键',
    `user_id`         BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `eat_time`        DATETIME        NOT NULL COMMENT '食用时间',
    `meal_type`       TINYINT         NOT NULL COMMENT '10早餐 15早加餐 20午餐 25午加餐 30晚餐 35夜宵',
    `food_name`       VARCHAR(200)    NOT NULL COMMENT '食物/菜品名称',
    `calories`        INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT '热量(kcal)',
    `protein`         DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT '蛋白质(g)',
    `fat`             DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT '脂肪(g)',
    `carbohydrate`    DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT '碳水(g)',
    `sugar`           DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT '糖(g)',
    `sodium`          DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT '钠(mg)',
    `fullness_score`  TINYINT UNSIGNED NULL COMMENT '饱腹感评分1~10',
    `location`        VARCHAR(100)    NOT NULL DEFAULT 'home' COMMENT '用餐地点，前端使用home/outside',
    `note`            VARCHAR(500)    NULL COMMENT '备注',
    `image_url`       VARCHAR(1000)   NULL COMMENT '食物图片地址',
    `deleted`         TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
    `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    KEY `idx_diet_user_eat_time` (`user_id`, `eat_time`, `deleted`),
    KEY `idx_diet_user_meal_time` (`user_id`, `meal_type`, `eat_time`),
    KEY `idx_diet_user_location_time` (`user_id`, `location`, `eat_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='饮食记录表';
