# Nacos ????
spring.cloud.nacos.config.server-addr=192.168.101.128:8848
spring.cloud.nacos.config.namespace=b78c8d52-3fc3-4276-9cbb-0f2efd326481
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=yaml
spring.cloud.nacos.config.refresh-enabled=true

# Nacos ????
spring.cloud.nacos.discovery.server-addr=192.168.101.128:8848
spring.cloud.nacos.discovery.namespace=b78c8d52-3fc3-4276-9cbb-0f2efd326481

# ??????????? YAML ?? config.import?
spring.config.import=optional:nacos:xxl-job-admin.properties?group=DEFAULT_GROUP&namespace=b78c8d52-3fc3-4276-9cbb-0f2efd326481